<?php
// api/rebuild_in_out.php

function rebuildInOutStatus($pdo) {
    try {
        // 1. Delete all ghost records (records generated by this script previously)
        // Ghost records are identifiable because they have no raw_data.
        $pdo->exec("DELETE FROM assets WHERE raw_data IS NULL OR raw_data = ''");

        // 2. Get all distinct periods and sort them chronologically
        $stmt = $pdo->query("SELECT DISTINCT periode_group FROM assets WHERE periode_group != 'Unknown Period'");
        $periods = $stmt->fetchAll(PDO::FETCH_COLUMN);
        
        usort($periods, function($a, $b) {
            return strtotime($a) - strtotime($b);
        });

        if (empty($periods)) return;

        // 3. Track active assets across time
        $activeAssets = []; // Reg No => Full Asset Row
        
        $updStmt = $pdo->prepare("UPDATE assets SET `in` = ?, `out` = ? WHERE id = ?");
        
        $insGhostStmt = $pdo->prepare("INSERT INTO assets (
            nama_perangkat, spec_code, reg_no, kategori, `in`, `out`, 
            asset_planner_organization, gr_date, nbv, since, days, `range`, 
            sub_location, grup_building, grup_rack, periode, periode_group, raw_data
        ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, NULL)");

        foreach ($periods as $period) {
            // Get all REAL records for this period
            $stmt = $pdo->prepare("SELECT * FROM assets WHERE periode_group = ? AND raw_data IS NOT NULL AND raw_data != ''");
            $stmt->execute([$period]);
            $currentRecords = $stmt->fetchAll(PDO::FETCH_ASSOC);
            
            $currentRegNos = [];
            
            foreach ($currentRecords as $rec) {
                $regNo = trim($rec['reg_no']);
                if (empty($regNo)) continue;
                
                $currentRegNos[$regNo] = true;
                
                // Determine IN/OUT status
                if (!isset($activeAssets[$regNo])) {
                    // New asset (First appearance)
                    $inStatus = 'IN';
                    $outStatus = '-';
                } else {
                    // Existing asset continuing into this period
                    $inStatus = '-';
                    $outStatus = '-';
                }
                
                // Update the actual DB record for this period
                $updStmt->execute([$inStatus, $outStatus, $rec['id']]);
                
                // Update our active tracking to the latest record details
                $activeAssets[$regNo] = $rec;
            }
            
            // Now, check for missing assets (went OUT)
            foreach ($activeAssets as $regNo => $prevRec) {
                if (!isset($currentRegNos[$regNo])) {
                    // It was active before, but is missing in the current period.
                    // Insert ghost record to show it as OUT in the current period!
                    $insGhostStmt->execute([
                        $prevRec['nama_perangkat'], $prevRec['spec_code'], $regNo, $prevRec['kategori'],
                        '-', 'OUT', // IN is '-', OUT is 'OUT'
                        $prevRec['asset_planner_organization'], $prevRec['gr_date'], $prevRec['nbv'],
                        $prevRec['since'], $prevRec['days'], $prevRec['range'],
                        $prevRec['sub_location'], $prevRec['grup_building'], $prevRec['grup_rack'],
                        $prevRec['periode'], $period
                    ]);
                    
                    // Remove from active assets so it doesn't keep getting marked as OUT in subsequent periods
                    unset($activeAssets[$regNo]);
                }
            }
        }
        
    } catch(Exception $e) {
        error_log("Failed to rebuild IN/OUT status: " . $e->getMessage());
    }
}
?>
